Update ci-byk-dsl.yml

diff --git a/.github/workflows/ci-byk-dsl.yml b/.github/workflows/ci-byk-dsl.yml
--- a/.github/workflows/ci-byk-dsl.yml
+++ b/.github/workflows/ci-byk-dsl.yml
@@ -454,32 +454,32 @@ jobs:
 
       - name: Push Docker image to ghcr
         run: docker push $DOCKER_TAG_CUSTOM
-  delete_old_images:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+#  delete_old_images:
+#    needs: build
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout Code
+#        uses: actions/checkout@v4
 
-      - name: Set up Docker
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.x'
+#      - name: Set up Docker
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: '3.x'
 
-      - name: Authenticate with GitHub Packages
-        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
+#      - name: Authenticate with GitHub Packages
+#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
 
-      - name: List Images
-        run: |
-              docker search docker.pkg.github.com/${{ github.repository }}/* || true # Use || true to prevent the workflow from failing if there are no images
-              docker images # List all Docker images to debug the issue
+#      - name: List Images
+#        run: |
+#              docker search docker.pkg.github.com/${{ github.repository }}/* || true # Use || true to prevent the workflow from failing if there are no images
+#              docker images # List all Docker images to debug the issue
 
 
-      - name: Delete Old Images
-        run: |
-          images_to_delete=$(tail -n +4 images.txt | head -n -3)
-          for image in $images_to_delete; do
-            echo "Deleting image: $image"
-            docker image rm "$image" --force
-          done
+ #     - name: Delete Old Images
+ #       run: |
+ #         images_to_delete=$(tail -n +4 images.txt | head -n -3)
+ #         for image in $images_to_delete; do
+ #           echo "Deleting image: $image"
+ #           docker image rm "$image" --force
+ #         done
 
